// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAij3GfTD60pKWnzTs4QWZFLElTEB3OCLc',
    appId: '1:75546032968:web:10fb2164d18ad2b515d17d',
    messagingSenderId: '75546032968',
    projectId: 'al-qemma-english-center',
    authDomain: 'al-qemma-english-center.firebaseapp.com',
    storageBucket: 'al-qemma-english-center.appspot.com',
    measurementId: 'G-1QV338ML40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2jMeIT6ypBtieVTC4Uqflfp4LP9jIfEA',
    appId: '1:75546032968:android:51227e0246ebff2815d17d',
    messagingSenderId: '75546032968',
    projectId: 'al-qemma-english-center',
    storageBucket: 'al-qemma-english-center.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCheCqRKVQ3bOXIxc5rZbxdsAM_KO-tZY',
    appId: '1:75546032968:ios:d27d6d2a411aef9b15d17d',
    messagingSenderId: '75546032968',
    projectId: 'al-qemma-english-center',
    storageBucket: 'al-qemma-english-center.appspot.com',
    iosClientId: '75546032968-ho5fehhl3e4svvtcgmeninqqo9vq8n8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.qemmaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCheCqRKVQ3bOXIxc5rZbxdsAM_KO-tZY',
    appId: '1:75546032968:ios:d27d6d2a411aef9b15d17d',
    messagingSenderId: '75546032968',
    projectId: 'al-qemma-english-center',
    storageBucket: 'al-qemma-english-center.appspot.com',
    iosClientId: '75546032968-ho5fehhl3e4svvtcgmeninqqo9vq8n8i.apps.googleusercontent.com',
    iosBundleId: 'com.example.qemmaMobile',
  );
}
