name: qemma_mobile
description: Al-Qemma English Center.

publish_to: 'none'

version: 1.0.1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bootstrap: ^2.0.0
  fl_chart: ^0.55.0
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  jiffy: ^5.0.0
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/user.png
    - assets/images/no_items.png
  
  fonts:
    - family: Droid Arabic Kufi
      fonts:
        - asset: assets/fonts/DroidArabicKufi.ttf
        - asset: assets/fonts/DroidArabicKufi2.ttf
          style: normal
